# Generated by Django 5.0.2 on 2024-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role_description',
            field=models.TextField(),
        ),
    ]
